### ISSUE TITLE
Cache-Control

### ISSUE THREAD

**Issue by denji** [agarzon/nginx-config#1]
* https://code.facebook.com/posts/557147474482256/this-browser-tweak-saved-60-of-requests-to-facebook/
* https://bitsup.blogspot.com/2016/05/cache-control-immutable.html

```nginx
# add_header Cache-Control "public,max-age=3600,immutable";
# add_header Cache-Control "public,max-age=604800,immutable";
add_header Cache-Control "public,max-age=31536000,immutable";
````

**Comment by agarzon** [comment]
Closing with https://github.com/agarzon/nginx-config/commit/94eba5a074bf24208116ab5cb7ceba2aec87a40b
