### ISSUE TITLE
HTTP_PROXY

### ISSUE THREAD

**Issue by denji** [agarzon/nginx-config#3]
Reset the `HTTP_PROXY` does not require, as the vulnerability is only in legacy programs that did not have security patches applied. The most correct way is to apply automatic security patches without updating the software.
* RHEL based: `yum-cron(update_cmd=security)`.
* Ubuntu: `unattended-upgrades` + `Unattended-Upgrade::Allowed-Origins { ... "${distro_id}:${distro_codename}-security"; ... }`.

**Comment by agarzon** [comment]
https://httpoxy.org/

Open for PR.

**Comment by agarzon** [comment]
Closing with https://github.com/agarzon/nginx-config/commit/94eba5a074bf24208116ab5cb7ceba2aec87a40b
